name: Backend Pipeline

on:
  pull_request:
    branches: [ "dev" ]
  push:
    branches: [ "workflow-update" ]   # ensure runs on your branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build backend Docker image
        run: docker build -t backend:${{ github.sha }} ./backend
